# Generated by Django 3.1.7 on 2021-05-31 22:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('podkrolestwo', models.CharField(max_length=20, null=True)),
                ('klasa', models.CharField(max_length=20, null=True)),
                ('rzad', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=20, null=True)),
                ('is_healthy', models.BooleanField(default='0', null=True)),
                ('is_fattening', models.BooleanField(default='0', null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.category')),
            ],
        ),
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recipes.category')),
                ('author', models.CharField(blank=True, max_length=35, null=True)),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('ScientificallyProven', models.BooleanField(default='0', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BadThings',
            fields=[
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recipes.category')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recipes.category')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(blank=True, max_length=35, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('title', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('steps', models.TextField(blank=True, null=True)),
                ('prep_time', models.DurationField()),
                ('servings', models.IntegerField()),
                ('difficulty', models.CharField(choices=[('ES', 'Easy'), ('MD', 'Medium'), ('HD', 'Hard')], default='ES', max_length=6)),
                ('author', models.CharField(blank=True, max_length=35, null=True)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.category')),
                ('ingredients', models.ManyToManyField(to='recipes.Ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.recipe')),
            ],
        ),
    ]
