# Generated by Django 3.1.7 on 2021-05-31 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='klasa',
            new_name='gromada',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='podkrolestwo',
            new_name='typ',
        ),
    ]
